apiVersion: v1 
kind: Pod
metadata:
  name: node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: hardware
            operator: In 
            values:
            - gpuuu
  containers:
  - name: node-affinity
    image: nginx